---

- name: Input expectations are verified
  assert:
    that:
        - 'rhsm | default("", True) | length'
        - 'rhsm.unsubscribe | default(True)'

- name: Attempt unsubscribing, never fail the host
  block:

    - name: System is  unsubscribed
      shell: subscription-manager unregister | true
      register: result
      ignore_errors: True
      when: not_check and rhsm.unsubscribe | default(True)

  rescue:
    - name: Any failed state cleared from all inventory hosts
      meta: clear_host_errors

    - name: Persistent connections are reset
      meta: reset_connection
