---

- name: Input expectations are verified
  assert:
    that:
        - 'inventory_hostname != "localhost"'
        - 'destruction_command is defined'
        - 'creation_destruction_environment is defined'
        - 'creation_destruction_asserts is defined'

# Allows customized checking of jinja templates / variables in cloud_provisioning_command
- name: Subject's list of optional creation_destruction_asserts are all true
  assert:
    that: '{{ creation_destruction_asserts }}'
  # Don't actually fail the task, still attempt to destroy subject
  ignore_errors: True
  when: creation_destruction_asserts | default('', True) | length

- name: Subject's destruction_command is executed
  shell: "{{ destruction_command.command | regex_replace('\\n', ' ') }}"
  environment: "{{ creation_destruction_environment if creation_destruction_environment | default('', True) | trim | length else {} }}"
  args:
    chdir: "{{ destruction_command.chdir | default(playbook_dir) }}"
    executable: "{{ destruction_command.executable | default(omit) }}"
    creates: "{{ destruction_command.creates | default(omit) }}"
    removes: "{{ destruction_command.removes | default(omit) }}"
  # There are many ways this could fail, allow play to attempt to continue
  failed_when: False
  register: result
  delegate_to: localhost
  when: destruction_command | default('', True) | trim | length

- name: The inventory is refreshed
  meta: refresh_inventory
