---
dist: trusty
language: python
python:
    - "2.7"

sudo: required

git:
    submodules: false

branches:
    only:
        - master

matrix:
    fast_finish: true
    include:
        - python: "2.7"
          env: SUITE="Typo Check"
        - python: "2.7"
          env: SUITE="Unit test"
        - python: "2.7"
          env: SUITE="System test"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq docker realpath

install:
    - ./.travis.sh install

script:
    - ./.travis.sh "$SUITE"
