---

dist: trusty
sudo: required
language: python
python:
    - "3.6"

services:
  - docker

branches:
    only:
        - master

env:
    matrix:
        - TEST: ./bin/typos.sh
        - TEST: ./bin/unittest.sh
        - TEST: ./bin/check.sh
    global:
        - DEBUG: true

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq realpath

script:
    - ./bin/run_ci_tests.sh
