---

sudo: required

services:
  - docker

branches:
    only:
        - master

matrix:
    fast_finish: true
    include:
        - env: SUITE="Typo Check"
        - env: SUITE="Unit test"
        - env: SUITE="System test"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq realpath

install:
    - ./.travis.sh install

script:
    - ./.travis.sh "$SUITE"
