---

- name: Attempt to unregister any subscribed hosts prior to destruction
  hosts: all
  strategy: free
  vars_files:
    - vars.yml

  tags:
    - cleanup

  pre_tasks:
    - name: All hosts are available for un-subscribing
      meta: clear_host_errors
      changed_when: true

  roles:
    - role: unsubscribed
      when: subject_created and
            rhsm | default("", True) | trim | length and
            rhsm.username | default("", True) | trim | length and
            rhsm.password | default("", True) | trim | length and
            rhsm.unsubscribe


- name: All hosts perform their destruction roles
  hosts: all
  strategy: free
  vars_files:
    - vars.yml

  tags:
    - cleanup

  pre_tasks:
    - name: All hosts are available for destruction
      meta: clear_host_errors
      changed_when: true

  roles:
    - role: collective_destroyed
      when: uuid is defined and
            inventory_hostname == 'localhost' and
            collective_destruction_command.command | default('', True) | trim | length

    - role: destroyed
      when: uuid is defined and
            inventory_hostname != 'localhost' and
            "permanent" not in group_names and
            subject_created | bool and
            not collective_created | default(False) | bool and
            cloud_destruction_command | default('', True) | trim | length

    - role: invcache
      ic_opr: 'delete'
