---

- include: '{{ playbook_dir }}/common.yml'

- name: Attempt to unregister any subscribed subjects
  hosts: subjects
  vars_files:
    - vars.yml
  tags:
    - cleanup
  roles:

    - role: unsubscribed
      when: subject_created and
            rhsm | default("", True) | trim | length and
            rhsm.username | default("", True) | trim | length and
            rhsm.password | default("", True) | trim | length and
            rhsm.unsubscribe


- name: Localhost performs any collective destruction before subject destruction
  hosts: localhost
  vars_files:
    - vars.yml
  tags:
    - cleanup
  pre_tasks:

    - name: Any failed state cleared from all inventory hosts
      meta: clear_host_errors
      changed_when: true

  roles:

    - role: collective_destroyed
      when: uuid is defined and
            collective_destruction_command | default('', True) | trim | length

  post_tasks:

    - name: Any failed state cleared from all inventory hosts
      meta: clear_host_errors
      changed_when: true

- name: Attempt to destroy subjects and cleanup all hostvarsfiles
  hosts: all
  vars_files:
    - vars.yml
  tags:
    - cleanup
  pre_tasks:

    - name: Any failed state cleared from all inventory hosts
      meta: clear_host_errors
      changed_when: true

  roles:

    - role: destroyed
      # Restoring hostvars file wipes out uuid, try destroying once only.
      when: uuid is defined and
            "subjects" in group_names and
            not collective_created | default(False) | bool and
            destruction_command | default("", True) | trim | length

  post_tasks:

    - name: Any failed state cleared from all inventory hosts
      meta: clear_host_errors
      changed_when: true

    - name: hostvarsfilebackup is restored to hostvarsfile
      command: 'mv "{{ hostvarsfilebackup }}" "{{ hostvarsfile }}"'
      delegate_to: localhost
      when: uuid is defined and
            not collective_created | default(False) | bool and
            (hostvarsfilebackup | default("", True) | trim | is_file or
             hostvarsfilebackup | default("", True) | trim | is_link)
