---

- name: Localhost is initialized, resets and joins all subjects to their join_groups
  hosts: localhost
  # Needed for --list-tags and --check
  gather_facts: "{{ hostvars is defined and hostvars.localhost.not_checking | default(False) }}"
  vars_files:
    - vars.yml
  tags:
    - cleanup
  pre_tasks:  # Some host may have failed a task
    - name: Any failed state cleared from all inventory hosts
      meta: clear_host_errors
      changed_when: true
  roles:
    - common

- name: Attempt to unregister any subscribed subjects
  hosts: subjects
  gather_facts: False  # Don't assume all hosts are reachable
  vars_files:
    - vars.yml
  tags:
    - cleanup
  roles:
    - role: unsubscribed
      when: rhsm | default("", True) | trim | length and
            rhsm.username | default("", True) | trim | length and
            rhsm.password | default("", True) | trim | length and
            rhsm.unsubscribe

- name: Localhost resets cache and all host status for destruction
  hosts: localhost
  vars_files:
    - vars.yml
  tags:
    - cleanup
  tasks:
    - name: Any failed state cleared from all inventory hosts
      meta: clear_host_errors
      changed_when: true

- name: Attempt to destroy all subjects
  hosts: subjects
  gather_facts: False  # Don't assume all hosts are reachable
  vars_files:
    - vars.yml
  tags:
    - cleanup
  roles:
    - role: destroyed
      # Restoring hostvars file wipes out uuid, try destroying once only.
      when: uuid is defined and
            destruction_command | default("", True) | trim | length
  post_tasks:
    - name: Subject's hostvarsfilebackup is restored to hostvarsfile
      command: 'mv "{{ hostvarsfilebackup }}" "{{ hostvarsfile }}"'
      delegate_to: localhost
      when: hostvarsfilebackup | default("", True) | trim | is_file or
            hostvarsfilebackup | default("", True) | trim | is_link

- name: Localhost hostvarsbackup is restored last
  hosts: localhost
  vars_files:
    - vars.yml
  tags:
    - cleanup
  tasks:
    - name: Localhost's hostvarsfilebackup is restored to hostvarsfile
      command: 'mv "{{ hostvarsfilebackup }}" "{{ hostvarsfile }}"'
      delegate_to: localhost
      when: uuid is defined and
            (hostvarsfilebackup | default("", True) | trim | is_file or
             hostvarsfilebackup | default("", True) | trim | is_link)
