---

- name: Attempt to unregister any subscribed hosts prior to destruction
  hosts: all
  strategy: free
  vars_files:
    - vars.yml

  tags:
    - cleanup

  pre_tasks:
    - name: All hosts are available for un-subscribing
      meta: clear_host_errors
      changed_when: true

  roles:
    - role: cevich.subscribed
      unsubscribe: True
      when: rhsm | default("", True) | trim | length and
            rhsm.username | default("", True) | trim | length and
            rhsm.password | default("", True) | trim | length and
            rhsm.unsubscribe


- name: All hosts perform their destruction tasks
  hosts: all
  vars_files:
    - vars.yml

  tags:
    - cleanup

  pre_tasks:
    - name: All hosts are available for destruction
      meta: clear_host_errors
      changed_when: true

  roles:
    - role: collective_destroyed
      when: uuid is defined and
            inventory_hostname == 'localhost' and
            collective_destruction_command.command | default('', True) | trim | length

    - role: destroyed
      when: uuid is defined and
            inventory_hostname != 'localhost' and
            not collective_created | default(False, True) | bool and
            destruction_command.command | default('', True) | trim | length and
            'destruction' in group_names

- name: All hosts remove themselves from static inventory cache
  hosts: all
  vars_files:
    - vars.yml

  tags:
    - cleanup

  pre_tasks:
    - name: All hosts are available for destruction
      meta: clear_host_errors
      changed_when: true

  post_tasks:
    - name: Host removes itself from static inventory cache
      ic_delete:
      when: "'destruction' in group_names"
