---

- name: Subjects apply domain-specific configuration roles
  hosts: subjects
  strategy: free  # speed is of the essence
  vars_files:
    - vars.yml

  tags:
    - configuration

  pre_tasks:
    - name: Status of setup touchstone is retrieved
      include_role:
        name: cevich.touchstone

  roles:
    # setup-contingent, domain-specific configuration roles go here.
    # role: foo
    # when: stone_touched
