---

- include: '{{ playbook_dir }}/common.yml'

- name: Subjects apply domain-specific configuration roles
  hosts: subjects
  strategy: free  # speed is of the essence
  vars_files:
    - vars.yml
  tags:
    - configuration

  roles:
    - accessible

    - touchstone

    # setup-contingent, domain-specific configuration roles go here.
    # role: foo
    # when: stone_touched
