---

- name: Control-Host and subject-hosts are created and initialized
  hosts: all
  vars_files:
    - vars.yml

  tags:
    - creation

  pre_tasks:
    - name: Facts are gathered for control-host
      setup:
        gather_subset: network
      when: "inventory_hostname == 'localhost'"

  roles:
    - role: control_host
      when: "inventory_hostname == 'localhost'"

    - role: subject_host
      when: "inventory_hostname == 'localhost'"

    - role: collective_created
      when: inventory_hostname == 'localhost' and
            collective_creation_command.command | default('', True) | trim | length

    - role: subject_host
      when: "inventory_hostname != 'localhost'"

    - role: created
      when: not subject_created | default(False) | bool and
            not collective_created | default(False) | bool and
            creation_command | default('', True) | trim | length


- name: Updated inventory subjects are accessible and ready for Ansible
  hosts: all
  vars_files:
    - vars.yml

  tags:
    - creation

  pre_tasks:
    - name: Inventory is refreshed to ensure consistent runtime state
      meta: refresh_inventory

  roles:
    - role: accessible

    - role: cevich.subscribed
      when: rhsm | default("", True) | trim | length and
            rhsm.username | default("", True) | trim | length and
            rhsm.password | default("", True) | trim | length

    - role: ansible_dependencies
      when: "inventory_hostname != 'localhost'"
