---

- name: Control-Host and static subject-hosts are initialized
  hosts: all
  vars_files:
    - vars.yml

  tags:
    - creation

  pre_tasks:
    - name: Facts are gathered for control-host
      setup:
        gather_subset: network
      when: "inventory_hostname == 'localhost'"

  roles:
    - role: control_host
      when: "inventory_hostname == 'localhost'"

    # role-order significant: Group-membership (esp. cloud-group) required for all
    # staticly-defined subject-hosts
    - role: subject_host


- name: Static and collective subbject-hosts are created
  hosts: all
  vars_files:
    - vars.yml

  tags:
    - creation

  roles:
    - role: created
      when: not subject_created | default(False) | bool and
            not collective_created | default(False) | bool and
            creation_command | default('', True) | trim | length

    - role: collective_created
      when: inventory_hostname == 'localhost' and
            collective_creation_command.command | default('', True) | trim | length


- name: Subjects are accessible and ready for Ansible
  hosts: all
  vars_files:
    - vars.yml

  tags:
    - creation

  roles:
    - role: subject_host

    - role: accessible

    - role: subscribed
      when: rhsm | default("", True) | trim | length and
            rhsm.username | default("", True) | trim | length and
            rhsm.password | default("", True) | trim | length

    - role: ansible_dependencies
      when: "inventory_hostname != 'localhost'"
