---

- include: '{{ playbook_dir }}/common.yml'

- name: Subjects are created
  hosts: subjects
  vars_files:
    - vars.yml
  tags:
    - creation
  roles:

    - role: created
      when: not subject_created


- name: Localhost performs collective creation
  hosts: localhost
  vars_files:
      - vars.yml
  tags:
    - creation
  roles:

    - collective_created

- name: Collective created hosts apply common roles
  include: '{{ playbook_dir }}/common.yml'

- name: Subjects are accessible and ready for Ansible
  hosts: subjects
  strategy: free  # speed is of the essence
  vars_files:
    - vars.yml
  tags:
    - creation

  roles:

    - accessible

    - role: subscribed
      when: subject_created and
            rhsm | default("", True) | trim | length and
            rhsm.username | default("", True) | trim | length and
            rhsm.password | default("", True) | trim | length

    - ansible_dependencies
