---

# N/B: These are installed into galaxy_roles b/c ansible.conf
#      roles_path setting.

- name: cevich.touchstone
  src: cevich.touchstone

- name: cevich.parallel_git_repos
  src: cevich.parallel_git_repos

- name: cevich.subscribed
  src: cevich.subscribed
