---

- name: Subjects perform testing roles
  hosts: subjects
  # Needed for --list-tags and --check
  vars_files:
    - vars.yml

  tags:
    - run

  pre_tasks:
    - name: Status of setup touchstone is retrieved
      include_role:
        name: cevich.touchstone

  roles:
    - role: tested
      when: stone_touched
