---

- name: Localhost is initialized, joins all subjects to their join_groups
  hosts: localhost
  vars_files:
    - vars.yml
  tags:
    - run
  roles:
    - common

- name: Primary testing roles are applied
  hosts: subjects
  # Needed for --list-tags and --check
  gather_facts: "{{ hostvars is defined and hostvars.localhost.not_checking | default(False) }}"
  vars_files:
    - vars.yml
  tags:
    - run
  roles:
    - common

    - accessible

    - touchstone

    # Only do the buisness when host has fully completed all setup tags
    - role: tested
      when: stone_touched and whatyasay | trim | length
