---

- include: '{{ playbook_dir }}/common.yml'

- name: Primary testing roles are applied
  hosts: subjects
  # Needed for --list-tags and --check
  vars_files:
    - vars.yml
  tags:
    - run
  roles:
    - accessible

    - cevich.touchstone

    # Only do the business when host has fully completed all setup steps
    - role: tested
      when: stone_touched
