---

- include: '{{ playbook_dir }}/common.yml'

- name: Subjects apply domain-specific setup roles
  hosts: subjects
  strategy: free  # speed is of the essence
  vars_files:
    - vars.yml
  tags:
    - setup
  roles:

    - accessible

    - role: touchstone
      vars:
        touch_touchstone: False

      # domain-specific setup roles go here.
      # role: foo
      # when: not stone_touched

    - role: touchstone
      vars:
        touch_touchstone: true
