---

- name: Input expectations are verified
  assert:
    that:
        - 'ansible_check_mode in [True,False]'
        - 'inventory_hostname != "localhost"'
        - 'ansible_dependencies | default("", True) | trim | length'

- name: Low-level Ansible setup module-dependencies are installed
  raw: $(type -P dnf || type -P yum || echo ) install -y {{ ansible_dependencies }} && touch "/tmp/.{{ role_path | basename }}"
  register: result
  args:
    executable: "/bin/bash"
    creates: "/tmp/.{{ role_path | basename }}"
  failed_when: False  # Any missing & required packages will show up as failures in the next task
  changed_when: result | success
  when: not ansible_check_mode

- name: Hosts facts are gathered, revealing any missing low-level Ansible dependencies
  setup:
    gather_subset: network
  when: not ansible_check_mode
