---

- name: Input expectations are verified
  assert:
    that:
        - 'hostvars.localhost.uuid is defined'

- name: The cloud_group variable is set from defaults when undefined
  set_fact:
    cloud_group: '{{ default_cloud_group }}'
  when: cloud_group is undefined

- name: Runtime variables updated for all subjects
  ic_update:
    ansible_check_mode: "{{ hostvars.localhost.ansible_check_mode }}"
    uuid: '{{ hostvars.localhost.uuid }}'
    cloud_group: "{{ cloud_group }}"
    join_groups: "{{ join_groups | default([], True) | union(['subjects', cloud_group]) }}"
    subject_created: '{{ False if subject_created is undefined else subject_created }}'
    collective_created: '{{ False if collective_created is undefined else collective_created }}'
  when: inventory_hostname != 'localhost' and
        not uuid | default("", True) | trim | length

- name: Critical expectations are verified
  assert:
    that:
      - 'uuid | trim | length'
      - 'uuid == hostvars.localhost.uuid'
      - 'subject_created | bool in [True, False]'
      - 'collective_created | bool in [True, False]'
      - 'ansible_check_mode | bool in [True, False]'
      - 'cloud_group | trim | length'

- name: Important control-host facts are logged for debugging
  debug:
    var: '{{ item }}'
  with_items:
    - uuid
    - groups
  when: "inventory_hostname == 'localhost'"
