---
# vim-syntax: ansible

- name: Ansible universal accessability command is executed
  raw: "/bin/true"
  register: result
  changed_when: result | success
  until: result | success
  retries: 5
  delay: 10
