---
# vim-syntax: ansible

- block:

    - name: Ansible accessability commands are executed
      include_tasks: command.yml
      with_items: '{{ accessable_test_cmds }}'
      loop_control:
        loop_var: accessable_test_cmd

  always:

    - name: Command result is debugged when it fails
      debug:
        var: result.results[-1]
      when: result | failed

    - name: Host fails when command retries exhausted
      fail:
        msg: Unable to verify accessability of {{ inventory_hostname }}
      when: result | failed
