---

- name: Input expectations are verified
  assert:
    that:
        - 'rhsm | default("", True) | length or ansible_check_mode'
        - 'rhsm.username | default("", True) | trim | length or ansible_check_mode'
        - 'rhsm.password | default("", True) | trim | length or ansible_check_mode'
        - 'role_path | is_dir'

- name: System is registered and subscribed
  raw: '{{ lookup("template", role_path ~ "/templates/sub-man-cmd.j2") | trim }}'
  failed_when: not_check or result.rc != 0 and
               not result.stderr | search("already registered")
  # Keep credentials out of logs
  no_log: True
  ignore_errors: True
  register: result
  when: rhsm | default('', True) | length

- name: The subscription-manager register command failed
  fail:
    msg: |
      subscription-manager register command failed
      exit: {{ result.rc }}
      stdout: {{ result.stdout }}
      stderr: {{ result.stderr }}
  when: result | failed and not_check
