---

# Can't pass strings to meta actions, have to check one-by-one

- name: Any failed state cleared from all inventory hosts
  meta: clear_host_errors

- name: Persistent connections are reset
  meta: reset_connection

- name: Gathered facts and fact-cache is cleared
  meta: clear_facts

- name: Reload of the inventory, including dynamic inventory scripts
  meta: refresh_inventory
