---

- name: Localhost verifies playbook compatibility
  assert:
    that:
        - 'inventory_hostname == "localhost"'
        - 'ansible_version | length'
        - 'ansible_version.string | version_compare("2.3", ">=")'
        - 'join_groups | default([], True) | length'
        - 'uuid_gen_cmd | default("", True) | trim | length'

- name: The collective_cloud_group value is buffered
  set_fact:
    collective_cloud_group: '{{ collective_cloud_group if collective_cloud_group | default("", True) | trim | length else default_collective_cloud_group }}'

- name: Localhost runtime variables are established
  ic_update:
    cloud_group: "all"
    ansible_check_mode: "{{ ansible_check_mode | default(False) }}"
    collective_cloud_group: '{{ collective_cloud_group }}'
    uuid: '{{ lookup("pipe", uuid_gen_cmd) | trim }}'
    join_groups: '{{ join_groups | default([], True) | union([collective_cloud_group ]) }}'
    subject_created: True
    collective_created: False
  when: not uuid | default("", True) | trim | length

- name: Control host initialization is confirmed
  assert:
    that:
        - 'uuid | trim | length'
        - 'collective_cloud_group | trim | length'
        - 'ansible_check_mode in [True, False]'
        - 'cloud_group == "all"'
        - 'subject_created | bool'
