---

creation_destruction_environment:
    WORKSPACE: '{{ playbook_dir }}'
    USER_CONFIG_DIR: '{{ lookup("env", "USER_CONFIG_DIR") | default("",True) }}'
    SITE_CONFIG_DIR: '{{ lookup("env", "SITE_CONFIG_DIR") | default("",True) }}'
    OS_CLIENT_CONFIG_FILE: '{{ lookup("env", "OS_CLIENT_CONFIG_FILE") | default("",True) }}'
    OS_CLOUD: '{{ lookup("env", "OS_CLOUD") | default("default",True) }}'
    OS_AUTH_URL: '{{ lookup("env", "OS_AUTH_URL") | default("",True) }}'
    OS_TENANT_ID: '{{ lookup("env", "OS_TENANT_ID") | default("",True) }}'
    OS_TENANT_NAME: '{{ lookup("env", "OS_TENANT_NAME") | default("",True) }}'
    OS_PROJECT_NAME: '{{ lookup("env", "OS_PROJECT_NAME") | default("",True) }}'
    OS_USERNAME: '{{ lookup("env", "OS_USERNAME") | default("",True) }}'
    OS_PASSWORD: '{{ lookup("env", "OS_PASSWORD") | default("",True) }}'
    OS_REGION_NAME: '{{ lookup("env", "OS_REGION_NAME") | default("",True) }}'

creation_destruction_asserts:
    - 'uuid | default("", True) | trim | length'
    - 'subject_image | default("", True) | trim | length'
    - 'subject_flavor | default("", True) | trim | length'
    - '"/usr/bin/virtualenv" | is_file'
    - 'ansible_private_key_file | default("", True) | trim | is_file'

creation_command:
    command: >
        bin/openstack_exclusive_create.py
        --lockdir=/tmp
        --image={{ subject_image | trim | quote }}
        --flavor={{ subject_flavor | trim | quote }}
        {{ "--size=" ~ subject_size | trim | quote if subject_size is defined else "" }}
        {{ "--userdata=" ~ subject_userdata | trim | quote if subject_userdata is defined else "" }}
        {{ inventory_hostname }}-{{ uuid }}
        {{ ansible_private_key_file | trim }}.pub
    chdir: "{{ playbook_dir }}"

destruction_command:
    command: "bin/openstack_destroy.py {{ inventory_hostname }}-{{ uuid }}"
    chdir: "{{ playbook_dir }}"
