---

# Lifted from -
# http://docs.ansible.com/ansible/latest/intro_inventory.html#list-of-behavioral-inventory-parameters

# All variables which make a host accessable to ansible.  These will be
# cleared to affect host removal
behavioral_inventory_parameters:
  - ansible_connection
  - ansible_host
  - ansible_port
  - ansible_user
  - ansible_ssh_pass
  - ansible_ssh_private_key_file
  - ansible_ssh_common_args
  - ansible_sftp_extra_args
  - ansible_scp_extra_args
  - ansible_ssh_extra_args
  - ansible_ssh_pipelining
  - ansible_ssh_executable
  - ansible_become
  - ansible_become_method
  - ansible_become_user
  - ansible_become_pass
  - ansible_become_exe
  - ansible_become_flags
  - ansible_shell_type
  - ansible_python_interpreter
  - ansible_shell_executable
  - ansible_docker_extra_args
