---

- name: The ansible_check_mode variable is set from localhost
  set_fact:
    ansible_check_mode: "{{ hostvars.localhost.ansible_check_mode }}"
  when: ansible_check_mode is undefined

- name: The canonical UUID for this run comes from localhost
  set_fact:
    uuid: '{{ hostvars.localhost.uuid }}'
  when: uuid is undefined

- name: The cloud_group variable is set from defaults
  set_fact:
    cloud_group: '{{ default_cloud_group }}'
  when: cloud_group is undefined

- name: This host's hostvarsfile variable is set when undefined
  set_fact:
    hostvarsfile: "{{ hostvars.localhost.inventory_dir }}/host_vars/{{ inventory_hostname }}.yml"
  when: hostvarsfile is undefined

- name: This host's hostvars file is loaded
  include_vars: '{{ hostvarsfile }}'

- name: This host's hostvarsfile backup filename is set when undefined
  set_fact:
    hostvarsfilebackup: '{{ hostvarsfile | dirname }}/.{{ hostvarsfile | basename }}~'
  when: hostvarsfilebackup is undefined

- name: Host is a member of groups from join_groups list plus cloud_group
  add_host:
    name: '{{ hostvars[item].inventory_hostname }}'
    groups: '{{ hostvars[item].join_groups | union([hostvars[item].cloud_group]) }}'
  with_items:
    - localhost
    - '{{ groups["subjects"] }}'
  delegate_to: localhost

- name: The subject_created flag is False when undefined
  set_fact:
    subject_created: False
  when: subject_created is undefined

- name: Common host_vars are cemented into hostvarsfile for all hosts
  include_role:
    name: host_vars_mod
  vars:
    source_role: "common"
    hostvarsfile_updates:
      # None of these should change during play, resolve all jinja2 template values
      uuid: '{{ hostvars.localhost.uuid }}'
      hostvarsfile: '{{ hostvarsfile }}'
      hostvarsfilebackup: '{{ hostvarsfilebackup }}'
      join_groups: '{{ join_groups | union([cloud_group]) }}'

- name: Critical expectations are verified
  assert:
    that:
      - 'uuid | default("", True) | trim | length'
      - 'subject_created is defined'
      - 'subject_created in [True, False]'
      - 'hostvarsfile is defined'
      - 'hostvarsfile | is_file'
      - 'ansible_check_mode | bool in [True, False]'

- name: Important host facts are logged for debugging
  debug:
    var: '{{ item }}'
  with_items:
    - uuid
    - subject_created
    - hostvarsfile

- name: Localhost debugs group membership
  debug:
    var: groups
  when: "inventory_hostname == 'localhost'"
