---

# N/B: Only fact setting / checking plus local action tasks may happen here

- name: The ansible_check_mode variable is inverted and buffered
  set_fact:
    not_checking: "{{ not ansible_check_mode | default(False) }}"

- name: This host's hostvarsfile variable is initialized.
  set_fact:
    hostvarsfile: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}.yml"
  when: hostvarsfile is undefined

- name: This host's hostvarsfile backup filename is defined
  set_fact:
    hostvarsfilebackup: '{{ hostvarsfile | dirname }}/.{{ hostvarsfile | basename }}~'

- name: Verify handling of certain incantations with this ansible version
  include: "check_mode.yml"
  when: ansible_check_mode | default(False)

- name: Common tasks exclusive to localhost are performed
  block:

    - name: The cloud_group variable is set from defaults
      set_fact:
        cloud_group: '{{ default_cloud_group }}'
      when: cloud_group is undefined

    - name: Localhost groups all subjects from their join_groups list
      add_host:
        name: '{{ item.inventory_hostname }}'
        groups: '{{ item.join_groups }}'
      when: item.join_groups | default('', True) | length
      with_items: "{{ groups['subjects'] | map('extract', hostvars) | list }}"
      no_log: True  # This is really noisy

    - name: The current epoch is buffered in hex-format to include miliseconds
      command: >
        python3 -c 'import time; print("{:x}".format(int(time.time()*1000)))'
      register: result

    - name: Buffer used as short/simple UUID to identify this playbook run
      set_fact:
        uuid: '{{ result.stdout | default(ansible_check_mode | string ) }}'
      when: uuid is undefined

    - name: Localhost's subject_created flag is always True
      set_fact:
        subject_created: True

    - name: Localhost input expectations are verified
      assert:
        that:
            - 'uuid | default("", True) | trim | length'
            - 'subject_created == True'
            - 'cloud_group is defined'
            - 'default_cloud_group | default("", True) | trim | length'
            - 'groups.subjects is defined'

  when: inventory_hostname == "localhost"

- name: All other host's common tasks are performed
  block:

    - name: The subject_created flag is False by default
      set_fact:
        subject_created: False
      when: subject_created is undefined

    - name: All hosts share the same playbook run UUID as localhost
      set_fact:
        uuid: '{{ hostvars.localhost.uuid }}'

  when: 'inventory_hostname != "localhost"'

- name: Common host_vars are cemented into hostvarsfile for all hosts
  include_role:
    name: host_vars_mod
  vars:
    source_role: "common"
    hostvarsfile_updates:
      # None of these should change during play, resolve all jinja2 template values
      uuid: '{{ hostvars.localhost.uuid }}'
      hostvarsfile: '{{ hostvarsfile }}'
      hostvarsfilebackup: '{{ hostvarsfilebackup }}'
      not_checking: "{{ not_checking | default(True) }}"

- name: Critical expectations are verified
  assert:
    that:
      - 'uuid | default("", True) | trim | length'
      - 'subject_created is defined'
      - 'subject_created in [True, False]'
      - 'hostvarsfile is defined'
      - 'hostvarsfile | is_file'
      - 'not_checking is defined'
      - 'not_checking in [True, False]'

- name: Important host facts are logged for debugging
  debug:
    var: '{{ item }}'
  with_items:
    - uuid
    - subject_created
    - hostvarsfile
    - groups
    - group_names
